//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_certificate
    {
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> PlayerSex { get; set; }
        public Nullable<System.DateTime> PlayerBirthday { get; set; }
        public string PlayerPrize { get; set; }
        public string PlayerDeclaration { get; set; }
        public string SchoolName { get; set; }
        public string PerformanceName { get; set; }
        public long V_ID { get; set; }
    }
}
