//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_voterMxJL
    {
        public Nullable<System.DateTime> VoterMXTime { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> VoterId { get; set; }
        public string VoterName { get; set; }
        public Nullable<int> VoterVotes { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> PlayerVotes { get; set; }
        public Nullable<int> PlayerSex { get; set; }
        public long V_ID { get; set; }
    }
}
